version: "2"
services:
  postgresql:
    image: postgres:11.2-alpine
    ports:
      - "5434:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  api-web: &api
    image: clojure-api-swagger-jwt:latest
    command: run
    depends_on:
      - postgresql
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    networks:
      - backend

  api-repl:
    <<: *api
    command: repl :headless :host 0.0.0.0 :port 7888
    depends_on:
      - api-web
    ports:
      - "7888:7888"
    networks:
      - backend

networks:
  backend:
    driver: bridge
